//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kzs.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int DaysTo2 {
            get {
                return ((int)(this["DaysTo2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("426")]
        public int DaysTo3 {
            get {
                return ((int)(this["DaysTo3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("912")]
        public int DaysTo4 {
            get {
                return ((int)(this["DaysTo4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DaysTo1 {
            get {
                return ((int)(this["DaysTo1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("([saliginis kodas] IN (\"06.3\", \"06.4\")) AND ({1} IS NULL)")]
        public string Where {
            get {
                return ((string)(this["Where"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FROM ssd")]
        public string From {
            get {
                return ((string)(this["From"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int DaysFrom2 {
            get {
                return ((int)(this["DaysFrom2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DaysFrom1 {
            get {
                return ((int)(this["DaysFrom1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("243")]
        public int DaysFrom3 {
            get {
                return ((int)(this["DaysFrom3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("730")]
        public int DaysFrom4 {
            get {
                return ((int)(this["DaysFrom4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT number, Linia, Kel, kilomrtras, piket, metras, siule, [saliginis kodas], P" +
            "ak_suv_data, 1 AS Kelintas FROM ssd WHERE ([saliginis kodas] IN (\"06.3\", \"06.4\")" +
            ") AND (I_pat_data IS NULL) AND (Pak_suv_data <= #{0:yyyy-MM-dd}#)")]
        public string Stm1 {
            get {
                return ((string)(this["Stm1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT number, Linia, Kel, kilomrtras, piket, metras, siule, [saliginis kodas], Pak_suv_data, 2 AS Kelintas FROM ssd WHERE ([saliginis kodas] IN (""06.3"", ""06.4"")) AND (I_pat_data IS NOT NULL) AND (II_pat_data IS NULL) AND (Pak_suv_data <= #{0:yyyy-MM-dd}#)")]
        public string Stm2 {
            get {
                return ((string)(this["Stm2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT number, Linia, Kel, kilomrtras, piket, metras, siule, [saliginis kodas], Pak_suv_data, 3 AS Kelintas FROM ssd WHERE ([saliginis kodas] IN (""06.3"", ""06.4"")) AND (II_pat_data IS NOT NULL) AND (III_pat_data IS NULL) AND (Pak_suv_data <= #{0:yyyy-MM-dd}#)")]
        public string Stm3 {
            get {
                return ((string)(this["Stm3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT number, Linia, Kel, kilomrtras, piket, metras, siule, [saliginis kodas], Pak_suv_data, 4 AS Kelintas FROM ssd WHERE ([saliginis kodas] IN (""06.3"", ""06.4"")) AND (III_pat_data IS NOT NULL) AND (IV_pat_data IS NULL) AND (Pak_suv_data <= #{0:yyyy-MM-dd}#)")]
        public string Stm4 {
            get {
                return ((string)(this["Stm4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Cols {
            get {
                return ((int)(this["Cols"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT id, linija, km, pk, m FROM Insps ORDER BY id")]
        public string StmInsps {
            get {
                return ((string)(this["StmInsps"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT stotis, linija, km, pk, m FROM Stotys ORDER BY stotis")]
        public string StmStotys {
            get {
                return ((string)(this["StmStotys"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT nr, stotis, linija, km, pk, m FROM Iesmai ORDER BY nr, stotis")]
        public string StmIesmai {
            get {
                return ((string)(this["StmIesmai"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01;254;377;;17;53;148;;22;1;15;;23;1;86;;24;1;11")]
        public string LineKms {
            get {
                return ((string)(this["LineKms"]));
            }
            set {
                this["LineKms"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>id</string>
  <string>linija</string>
  <string>kelias</string>
  <string>km</string>
  <string>pk</string>
  <string>m</string>
  <string>siule</string>
  <string>skodas</string>
  <string>suvdata</string>
  <string>data1</string>
  <string>data2</string>
  <string>data3</string>
  <string>data4</string>
</ArrayOfString>")]
        public string[] Mapping {
            get {
                return ((string[])(this["Mapping"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("suvirinimai")]
        public string WorksheetName {
            get {
                return ((string)(this["WorksheetName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A5")]
        public string TopLeftCell {
            get {
                return ((string)(this["TopLeftCell"]));
            }
        }
    }
}
