//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspectedOnes.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT number AS id, Linia AS linija, Kel AS kel, kilomrtras AS km, piket AS pk, metras AS m, siule AS siule, [saliginis kodas] AS skodas, I_pat_data AS pdata, I_pat_aparat AS aparat, I_pat_operator AS operat, 1 AS kelintas
FROM ssd 
WHERE (I_pat_data BETWEEN #{0:yyyy-MM-dd}# AND #{1:yyyy-MM-dd}#) AND (LEFT([saliginis kodas], 1) <> ""x"")

UNION

SELECT number AS id, Linia AS linija, Kel AS kel, kilomrtras AS km, piket AS pk, metras AS m, siule AS siule, [saliginis kodas] AS skodas, II_pat_data AS pdata, II_pat_aparat AS aparat, II_pat_operator AS operat, 2 AS kelintas
FROM ssd 
WHERE (II_pat_data BETWEEN #{0:yyyy-MM-dd}# AND #{1:yyyy-MM-dd}#) AND (LEFT([saliginis kodas], 1) <> ""x"")

UNION

SELECT number AS id, Linia AS linija, Kel AS kel, kilomrtras AS km, piket AS pk, metras AS m, siule AS siule, [saliginis kodas] AS skodas, III_pat_data AS pdata, III_pat_aparat AS aparat, III_pat_operaqtor AS operat, 3 AS kelintas
FROM ssd 
WHERE (III_pat_data BETWEEN #{0:yyyy-MM-dd}# AND #{1:yyyy-MM-dd}#) AND (LEFT([saliginis kodas], 1) <> ""x"")

UNION

SELECT number AS id, Linia AS linija, Kel AS kel, kilomrtras AS km, piket AS pk, metras AS m, siule AS siule, [saliginis kodas] AS skodas, IV_pat_data AS pdata, IV_pat_aparat AS aparat, IV_pat_operator AS operat, 4 AS kelintas
FROM ssd 
WHERE (IV_pat_data BETWEEN #{0:yyyy-MM-dd}# AND #{1:yyyy-MM-dd}#) AND (LEFT([saliginis kodas], 1) <> ""x"")

ORDER BY operat, pdata, skodas, linija, kel, km, pk, m, siule;")]
        public string FetcherSql {
            get {
                return ((string)(this["FetcherSql"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>id</string>
  <string>linija</string>
  <string>kel</string>
  <string>km</string>
  <string>pk</string>
  <string>m</string>
  <string>siule</string>
  <string>skodas</string>
  <string>pdata</string>
  <string>aparat</string>
  <string>operat</string>
  <string>kelintas</string>
</ArrayOfString>")]
        public string[] MappingDb {
            get {
                return ((string[])(this["MappingDb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A8")]
        public string TopLeftCell {
            get {
                return ((string)(this["TopLeftCell"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>id</string>
  <string>linija</string>
  <string>kel</string>
  <string>km</string>
  <string>pk</string>
  <string>m</string>
  <string>siule</string>
  <string>skodas</string>
  <string>kelintas</string>
  <string>aparat</string>
  <string>pdata</string>
</ArrayOfString>")]
        public string[] MappingTemplate {
            get {
                return ((string[])(this["MappingTemplate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("template")]
        public string TemplateSheetName {
            get {
                return ((string)(this["TemplateSheetName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM operatoriai")]
        public string GetOperatorsSql {
            get {
                return ((string)(this["GetOperatorsSql"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Patikrino operatorius - {0} (kodas {1})")]
        public string OperatorFormat {
            get {
                return ((string)(this["OperatorFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A5")]
        public string OperatorRange {
            get {
                return ((string)(this["OperatorRange"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";")]
        public string CsvDelimiter {
            get {
                return ((string)(this["CsvDelimiter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ID</string>
  <string>Linija</string>
  <string>Kelias</string>
  <string>Km</string>
  <string>Pk</string>
  <string>M</string>
  <string>Siule</string>
  <string>Salyg_kodas</string>
  <string>Kelintas</string>
  <string>Defektoskopas</string>
  <string>Patikr_data</string>
</ArrayOfString>")]
        public string[] CsvColumnTitles {
            get {
                return ((string[])(this["CsvColumnTitles"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("patikrinti_{0:yyyyMMdd}-{1:yyyyMMdd}.xlsx")]
        public string DefaultXlsxFNFormat {
            get {
                return ((string)(this["DefaultXlsxFNFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("patikrinti_{0:yyyyMMdd}-{1:yyyyMMdd}.csv")]
        public string DefaultCsvFNFormat {
            get {
                return ((string)(this["DefaultCsvFNFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT number AS id
FROM ssd 
WHERE (I_pat_data BETWEEN #{0:yyyy-MM-dd}# AND #{1:yyyy-MM-dd}#) AND (LEFT([saliginis kodas], 1) <> ""x"") AND (I_pat_aparat IS NULL OR I_pat_operator IS NULL)

UNION

SELECT number AS id
FROM ssd 
WHERE (II_pat_data BETWEEN #{0:yyyy-MM-dd}# AND #{1:yyyy-MM-dd}#) AND (LEFT([saliginis kodas], 1) <> ""x"") AND (II_pat_aparat IS NULL OR II_pat_operator IS NULL)

UNION

SELECT number AS id
FROM ssd 
WHERE (III_pat_data BETWEEN #{0:yyyy-MM-dd}# AND #{1:yyyy-MM-dd}#) AND (LEFT([saliginis kodas], 1) <> ""x"") AND (III_pat_aparat IS NULL OR III_pat_operaqtor IS NULL)

UNION

SELECT number AS id
FROM ssd 
WHERE (IV_pat_data BETWEEN #{0:yyyy-MM-dd}# AND #{1:yyyy-MM-dd}#) AND (LEFT([saliginis kodas], 1) <> ""x"") AND (IV_pat_aparat IS NULL OR IV_pat_operator IS NULL)

ORDER BY id;")]
        public string BadDataSql {
            get {
                return ((string)(this["BadDataSql"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int FetcherSqlColumnCount {
            get {
                return ((int)(this["FetcherSqlColumnCount"]));
            }
        }
    }
}
